export type FormaErrorCode =
  | "INVALID_INPUT"
  | "PRODUCT_CONFIG_INCOMPLETE"
  | "PRODUCT_MUTATION_LOCKED"
  | "PRODUCT_DELETION_RECOVERY_FAILED"
  | "BASELINE_SEMANTIC_CONTRACT_CONFLICT"
  | "DESIGN_SESSION_ACTIVE"
  | "DESIGN_SESSION_AUDIT_LINK_MISSING"
  | "DESIGN_COMMIT_RECOVERY_REQUIRED"
  | "COMPONENT_LIBRARY_VERSION_MISSING"
  | "COMPONENT_LIBRARY_METADATA_MISSING"
  | "COMPONENT_LIBRARY_LATEST_MISSING"
  | "COMPONENT_LIBRARY_INVALID"
  | "COMPONENT_SEED_REQUIRED"
  | "LOCK_CORRUPT"
  | "STRICT_SCHEMA_VALIDATION_FAILED"
  | "REQUIREMENT_STATUS_INVALID"
  | "DOCUMENT_EMPTY"
  | "PAGES_EMPTY"
  | "PAGE_NOT_OWNED"
  | "PEN_FILE_INVALID"
  | "PAGE_NOT_DONE"
  | "DESIGN_MODE_INVALID"
  | "NODE_NOT_FOUND"
  | "EXPORT_FORMAT_UNSUPPORTED"
  | "VERSION_TOO_LOW"
  | "HISTORY_FILE_MISSING"
  | "PRODUCT_NOT_FOUND"
  | "REQUIREMENT_NOT_FOUND"
  | "DESIGN_NOT_FOUND"
  | "STYLE_NOT_FOUND"
  | "SYNC_ALREADY_RUNNING"
  | "SYNC_GIT_NOT_FOUND"
  | "PENCIL_CLI_NOT_FOUND"
  | "PENCIL_NOT_AUTHENTICATED"
  | "PENCIL_CAPABILITY_UNAVAILABLE"
  | "PENCIL_APP_REQUIRED"
  | "FORBIDDEN_PATH_PARAMETER"
  | "MANUAL_EDIT_DETECTED"
  | "DESIGN_CANVAS_CHANGED"
  | "PENCIL_LOCK_HELD"
  | "PAGE_FRAME_AMBIGUOUS"
  | "PAGE_FRAME_MISMATCH"
  | "PAGE_FRAME_NOT_FOUND"
  | "PENCIL_SCHEMA_INVALID"
  | "PENCIL_COLOR_INVALID"
  | "PENCIL_PROPERTY_INVALID"
  | "DESIGN_LAYOUT_INVALID"
  | "DESIGN_SCOPE_VIOLATION"
  | "PREVIEW_EXPORT_FAILED"
  | "PREVIEW_NOT_EXPORTED"
  | "SEMANTIC_SCOPE_CHANGED"
  | "UNMANAGED_METADATA_NORMALIZATION_REQUIRED"
  | "COMPONENT_USAGE_UNLINKED"
  | "COMPONENT_LIBRARY_UNMAPPED"
  | "COMPONENT_CONTRACT_CHANGED"
  | "COMPONENT_OVERRIDE_CONFLICT"
  | "COMPONENT_REFRESH_PARTIAL_BLOCKED"
  | "COMPONENT_REFRESH_UNSAFE"
  | "ARTIFACT_WRITE_FAIL"
  | "ARTIFACT_ALREADY_EXISTS"
  | "ARTIFACT_NOT_FOUND"
  | "OD_RUNTIME_FAILED"
  | "OD_RUNTIME_TIMEOUT";

export class FormaError extends Error {
  constructor(
    public readonly code: FormaErrorCode,
    message: string,
    public readonly details: Record<string, unknown> = {}
  ) {
    super(message);
    this.name = "FormaError";
  }

  toJSON() {
    return { error_code: this.code, message: this.message, details: this.details };
  }
}
